/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as SquadRouteImport } from './routes/squad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/campaign': typeof CampaignRoute
  '/season': typeof SeasonRoute
  '/squad': typeof SquadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/campaign': typeof CampaignRoute
  '/season': typeof SeasonRoute
  '/squad': typeof SquadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/campaign': typeof CampaignRoute
  '/season': typeof SeasonRoute
  '/squad': typeof SquadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battle' | '/campaign' | '/season' | '/squad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle' | '/campaign' | '/season' | '/squad'
  id: '__root__' | '/' | '/battle' | '/campaign' | '/season' | '/squad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
  CampaignRoute: typeof CampaignRoute
  SeasonRoute: typeof SeasonRoute
  SquadRoute: typeof SquadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
  CampaignRoute: CampaignRoute,
  SeasonRoute: SeasonRoute,
  SquadRoute: SquadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
